name: synadart
version: 0.5.0

description: >-
  A limited but fully documented neural network library created for educational
  purposes.

homepage: https://github.com/vxern/synadart
repository: https://github.com/vxern/synadart
issue_tracker: https://github.com/vxern/synadart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  words: ^0.4.4
