name: synadart
version: 0.4.3

description: >-
  A simple-to-grasp, complete and fully documented Neural Network library, 
  written from scratch in Dart.

homepage: https://github.com/wordcollector/synadart
repository: https://github.com/wordcollector/synadart
issue_tracker: https://github.com/wordcollector/synadart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Logging
  sprint: ^1.0.3

dev_dependencies:
  words: ^0.0.2+1
