name: synadart
description: Library for creating neural networks, with a purely Dart implementation.
version: 0.4.1+1
homepage: https://github.com/vxern/synadart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Logging
  sprint: ^1.0.0+1

dev_dependencies:
  pedantic: ^1.11.0
