publish_to: https://pub.dev

name: synadart
version: 0.4.1+1

description: Library for creating neural networks, with a purely Dart implementation.

homepage: https://github.com/vxern/synadart
repository: https://github.com/vxern/synadart
issue_tracker: https://github.com/vxern/synadart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Logging
  sprint: ^1.0.2+3

dev_dependencies:
  words: ^0.0.2+1
